log:
  level: info

authentication:
  required: true
  exclude:
    evaluation: true
  methods:
    token:
      enabled: true
      storage:
        tokens:
          index_app:
            credential: "${env:FLIPT_API_TOKEN}"
            metadata:
              description: "Index app read/write"

storage:
  default:
    backend:
      type: local
      path: /var/opt/flipt
